version: "3.4"
services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:80"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - ./server/app:/code/app
    links:
      - db-postgres:db-postgres

  db-postgres:
    image: postgis/postgis:16-3.4-alpine
    env_file: .env
    volumes:
      - ./data/db:/data
    ports:
      - "5432:5432"

