name: Build and Push Docker Image

on:
  pull_request:
    paths:
      - 'server/**'
  release:
    types: [published]

env:
  IMAGE_NAME: digitalearthafrica/waterbodies-api

jobs:
  build-and-push:
    name: Build Docker image and push to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DEAFRICA_DOCKER_PASSWORD }}

    - name: Get Git release version
      id: get_git_release
      run: |
        git fetch --tags
        GIT_RELEASE_VERSION=$(git tag --sort version:refname | tail -1)
        if [ "${GIT_RELEASE_VERSION}" == "" ] ; then
          GIT_RELEASE_VERSION="v0.0.1"
        fi
        echo "git_release=${GIT_RELEASE_VERSION}" >> "$GITHUB_OUTPUT"

    - name: Build Docker image
      run: |
        cd server
        docker build -t ${IMAGE_NAME} .

    - name: Tag & push Docker image
      id: tag_push_docker_image
      env:
        GIT_RELEASE: ${{ steps.get_git_release.outputs.git_release }}
        GIT_EVENT_NAME:  ${{ github.event_name }}
        PR_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        echo "Latest release: ${GIT_RELEASE}"
        COMMIT_SHA=$(echo ${PR_COMMIT_SHA:0:7})
        if [ ${GIT_EVENT_NAME} == "pull_request" ] ; then
          NEW_TAG="${GIT_RELEASE}-${COMMIT_SHA}-$(date +%s)"
        else
          NEW_TAG="${GIT_RELEASE}"
        fi
        docker tag ${IMAGE_NAME} ${IMAGE_NAME}:${NEW_TAG}
        docker push ${IMAGE_NAME}:${NEW_TAG}
        echo "::set-output name=NEW_TAG::${NEW_TAG}"
        echo "::set-output name=IMAGE_NAME::${IMAGE_NAME}"

    - name: Configure AWS Credentials and Login to Amazon ECR
      id: aws-ecr-login
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Tag and Push Docker image to ECR
      env: 
        NEW_TAG: ${{ steps.tag_push_docker_image.outputs.NEW_TAG }}
        IMAGE_NAME: ${{ steps.tag_push_docker_image.IMAGE_NAME }}
      run: |
        docker tag ${IMAGE_NAME}:${NEW_TAG} 543785577597.dkr.ecr.af-south-1.amazonaws.com/${IMAGE_NAME}:${NEW_TAG}
        docker push 543785577597.dkr.ecr.af-south-1.amazonaws.com/${IMAGE_NAME}:${NEW_TAG}